### ISSUE TITLE
Allow an array of properties, not just one

### ISSUE THREAD

**Issue by davidtheclark** [sh-waqar/stylelint-declaration-use-variable#1]
Am I right that you currently cannot do `"declaration-use-variable": ["color", "background-color"]`?

I think that's probably a necessary feature. Have a look at stylelint's `property-value-blacklist` or `property-value-whitelist` for examples.

**Comment by sh-waqar** [comment]
@davidtheclark - I was thinking about it too. I will update it. Thanks.

**Comment by anthonykirkham** [comment]
+1 for this feature

**Comment by sh-waqar** [comment]
@anthonykirkham - Thanks for your input and using stylelint-declaration-use-variable. I have busy lately and didn't got the chance to work on this. I will update it soon.

**Comment by cehter** [comment]
I have the following Multiple properties: `"declaration-use-variable": ["/color/", "z-index", "/font/", "/margin/", "/padding/"],` It finds the color, but not the other properties. If I remove `/color/` I get the errors from `z-index`, so it seems that it takes just the first property. I did run your tests, but they work fine. 
Do you have any idea what the problem could be?

**Comment by ohskylab** [comment]
@cehter I just ran into this, raised more details and temporary workaround at #8.
