### ISSUE TITLE
Accepting color functions too would be great

### ISSUE THREAD

**Issue by rvetere** [sh-waqar/stylelint-declaration-use-variable#10]
In some situations i don't like to introduce a new variable and much more prefer to alter an existing one by color-functions.

Right now, something like this is still considered as an error by the plugin:
`background-color: color($white shade(5%));`

Would be awesome if a construct like this could be seen valid too.

**Comment by sh-waqar** [comment]
@rvetere - I have merged your PR but just got in my mind that if we update the documentation that would be great. Can you please create another PR updating the README docs related to the feature you have added. Thanks

**Comment by rvetere** [comment]
Good catch! I've just opened another PR for that 👍
