### ISSUE TITLE
Readme add

### ISSUE THREAD

**Issue by nicothin** [sh-waqar/stylelint-declaration-use-variable#13]
Please specify in the readme, that this tool does not find a match variable values in CSS-properties. This tool only verifies the use or non-variable for these properties.
(It would be nice to be notified in the form of linter "You used #dddddd, but you have a variable $gray-dark with this color"!)

**Comment by sh-waqar** [comment]
@nicothin - Thanks for the suggestion man. That is something ideal that I wanted to do at first but I could not get my head around it on how to make it possible.

If you have any suggestions on how to make it possible (the notification for already available color) that would be really helpful! I will try to explore few stuff in my free time as well.

**Comment by sh-waqar** [comment]
I can get very cool or I would say cooler if the plugin can even check for close matching colors like #eeeeee and #efeeee would somewhat give the same result.

**Comment by ai** [comment]
After reading README.md I have one question: does this plugin check that *value* was in some variable? Or it just force developer to always use variables?

For example, how many warnings I will get in this example:

```css
$color: blue;
a {
  color: blue;
}
b {
  color: red;
}
```

**Comment by sh-waqar** [comment]
@ai - It only gives warning when there is no variable is used or you can say it forces developers to use variables. 

I above example you will get 2 warnings.

**Comment by sh-waqar** [comment]
The plugin right now is not smart enough to detect that the assigned color is already been declared as a variable. And as I said that is something ideal.

**Comment by ai** [comment]
Hm. I think you should make README more clear.

Right now first example show me different behavior.

**Comment by sh-waqar** [comment]
@ai - Yes you are right. I give kind of a false perception. I will update it.

**Comment by sh-waqar** [comment]
@nicothin - So, now the plugin will notify you if there is a present variable with the same value already present in your code. For instance, you write `color: #fff` and you already have `$color-white: #fff` the plugin will give you error to use `$color-white` variable.

**Comment by sh-waqar** [comment]
Please try it out and let me know if it works for you.
