### ISSUE TITLE
SCSS color functions throws error

### ISSUE THREAD

**Issue by AndyOGo** [sh-waqar/stylelint-declaration-use-variable#17]
I have code like:

````scss
color: darken($color-white, 10%);
````

Which throws:
````sh
104:5     ✖     Expected variable for "color".    sh-waqar/declaration-use-variable
````

**Comment by jitendravyas** [comment]
I am also getting this issue

**Comment by AndyOGo** [comment]
@jitendravyas 
I created my own tool for this cause of this and other issues.
Check it out -> [`stylelint-declaration-strict-value`](https://www.npmjs.com/package/stylelint-declaration-strict-value)

**Comment by amk221** [comment]
I'm also affected by this:

```scss
color: rgba($foo-color, .5);
```

**Comment by sh-waqar** [comment]
we just released a new update and ignoring specific values or patterns are now supported 🎉 

You can use it like:
```
"sh-waqar/declaration-use-variable": [['/color/', 'font-size', 'z-index', { ignoreValues: ['/^darken/'] }]]
```

I am closing this issue. Feel free to re-open if you think it does not fulfill your requirement.
