### ISSUE TITLE
Ignore "inherit" value

### ISSUE THREAD

**Issue by alex-pex** [sh-waqar/stylelint-declaration-use-variable#19]
The linter should allow `color: inherit` without warning.

I don't want to declare `$inherit: inherit`, or `// stylelint-disable-next-line sh-waqar/declaration-use-variable` everytime I inherit values.

Can you ignore this specific value? Or allow a whitelist of allowed values, like:
```
"sh-waqar/declaration-use-variable": [{"/color/": ['inherit', 'transparent', 'black', 'white'], "font-family": ['inherit']}]
```

**Comment by alex-pex** [comment]
If you're interested, the issue is solved on a fork : https://github.com/sh-waqar/stylelint-declaration-use-variable/issues/14#issuecomment-265519817

It's the same whitelist idea but wiser

**Comment by weaintplastic** [comment]
+1

**Comment by amk221** [comment]
+1

**Comment by sh-waqar** [comment]
@alex-pex  - we just released a new update and ignoring specific values are now supported 🎉 

You can use it like:
```
"sh-waqar/declaration-use-variable": [['/color/', 'font-size', 'z-index', { ignoreValues: ['transparent', 'inherit'] }]]
```

I am closing this issue. Feel free to re-open if you think it does not fulfill your requirement.
