### ISSUE TITLE
Allow regexps as properties

### ISSUE THREAD

**Issue by davidtheclark** [sh-waqar/stylelint-declaration-use-variable#2]
Somebody could declare `"declaration-use-variable": ["/color/"]` and that would cover both `color` and `background-color`.

If you want to give this a shot, there is a util in stylelint that makes this easy: `matchesStringOrRegExp()`. Have a look at stylelint's `property-value-blacklist` or `property-value-whitelist` for examples.

**Comment by sh-waqar** [comment]
@davidtheclark - Good suggestion. Will take a look.
