### ISSUE TITLE
Allow custom exceptions per property

### ISSUE THREAD

**Issue by ixley** [sh-waqar/stylelint-declaration-use-variable#21]
I was really happy to find this plugin and have started implementing some rules, but also quickly came across instances where I wanted to be able to add custom value exceptions for certain properties.

For example:
- I want to force variable usage for `border-radius`, `margin`, `padding`, etc. but want to allow an exception for `0` (and `auto` for margin) – I can of course create variables for `0` and `auto`, but they feel like unnecessary abstractions in these cases.
- I want to force variables with colors, but also want to exclude values such as `#fff` and `#000`, or `transparent` or `inherit`, which again, I can add as variables, but which feel like unhelpful abstractions.

Any reasonable possibility of allowing for common or custom exceptions like this? I do acknowledge there are pretty trivial workarounds like just creating variables for these few cases, but I thought I'd check!

**Comment by chapati23** [comment]
We also need this. Our styles are scattered with `/* stylelint-disable-next-line sh-waqar/declaration-use-variable */`

I'd say `transparent` and `inherit` are pretty common values to reset or override colors where it doesn't make sense to use variables.

Any pointers to where one might add such an exception into the rule? Could try to take a stab at it with some guidance.

**Comment by robertjk** [comment]
The same: while I would love to disallow using `#rrggbb` colors as `color` properties values, some other values like `inherit` or `transparent` are acceptable and desired. Current rule doesn't seem to allow to allow this scenario.

**Comment by sh-waqar** [comment]
@ixley - we just released a new update and ignoring specific values are now supported 🎉 

You can use it like:
```
"sh-waqar/declaration-use-variable": [['/color/', 'font-size', 'z-index', { ignoreValues: ['transparent', 'inherit'] }]]
```

I am closing this issue. Feel free to re-open if you think it does not fulfill your requirement.
