### ISSUE TITLE
stylelint as peerDependencies

### ISSUE THREAD

**Issue by dartess** [sh-waqar/stylelint-declaration-use-variable#36]
Hello!
`stylelint` sounds like `peerDependencies`, not `dependencies`.
In the readme you can describe the need to install `stylelint` to use your plugin (like [this](https://github.com/csstools/stylelint-media-use-custom-media) or [this](https://github.com/hudochenkov/stylelint-order)).
Due to the use of `stylelint` as the main dependency, duplicate packages appear in projects:

```
> npm ls stylelint   
...
├── stylelint@13.6.1 
└─┬ stylelint-declaration-use-variable@1.7.2
  └── stylelint@11.1.1 
```

**Comment by AndyOGo** [comment]
@dartess 
Stylelknt is correctly added as peer dependency here:
https://github.com/AndyOGo/stylelint-declaration-strict-value

**Comment by iegik** [comment]
#50
