### ISSUE TITLE
Add support for other variable syntaxes?

### ISSUE THREAD

**Issue by jeddy3** [sh-waqar/stylelint-declaration-use-variable#4]
Firstly, thanks again for contributing to the stylelint ecosystem :)

Currently it only checks *sass-like* syntax (e.g. `$var-name`), used in the likes of `sass` and [`postcss-simple-vars`](https://github.com/postcss/postcss-simple-vars). Do you think adding support for *less-like* vars (e.g. `@var-name`) and [*custom properties*](https://www.w3.org/TR/css-variables/) (e.g. `var(--var-name)`) is a good idea?

**Comment by sh-waqar** [comment]
@jeddy3 - No problem at all :) it was my first open source project and I started from stylelint :)

:+1: for the suggestion. I will update the code to check for sass, less and custom properties you mentioned.

**Comment by jeddy3** [comment]
Excellent. There's a util in stylelint for checking if a word is a variable:

https://github.com/stylelint/stylelint/blob/master/src/utils/cssWordIsVariable.js

@davidtheclark Am I right in thinking that only a handful of these utils are exposes to the public API?
