### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [sh-waqar/stylelint-declaration-use-variable#40]
There hasn't been any meaningful activity by @sh-waqar in this repo for over a year. There are 2 unmerged PRs. Should someone fork it and publish an alternative that's maintained?

**Comment by AndyOGo** [comment]
@R0LA1mRifcF8yAkk 
I have completely rewrote my own plugin with additional features. Check it out here:
https://github.com/AndyOGo/stylelint-declaration-strict-value

**Comment by R0LA1mRifcF8yAkk** [comment]
Noted, thanks!
