### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by jeddy3** [sh-waqar/stylelint-declaration-use-variable#5]
As David mentioned in the other issues, this plugin follows the same mould as [`property-value-blacklist`](https://github.com/stylelint/stylelint/blob/master/src/rules/property-value-blacklist/README.md) and [`property-value-whitelist`](https://github.com/stylelint/stylelint/blob/master/src/rules/property-value-whitelist/README.md) rules.

For consistency with these existing rules you might want to rename your plugin to `stylelint-property-value-use-variable`.

**Comment by sh-waqar** [comment]
@jeddy3 - Sure I will update the name of my plugin to `stylelint-property-value-use-variable`. Its kinda look :D but it goes with the naming convention for stylelint.

**Comment by jeddy3** [comment]
Actually, I think you're right. That name isn't very good.

Either stick with `declaration-use-variable` or perhaps make it a little clearer with `declaration-use-variable-for-value` as, I think, variables can also be used for properties in scss and less.
