### ISSUE TITLE
Rename to use namespace

### ISSUE THREAD

**Issue by bdukes** [sh-waqar/stylelint-declaration-use-variable#6]
When I use this plugin, it shows an error:

>Plugin rules that aren't namespaced have been deprecated, and in 7.0 they will be disallowed.

According to http://stylelint.io/developer-guide/plugins/, you can use the namespace `plugin/` if there's not another namespace that makes sense, so either `plugin/declaration-use-variable` or `sh-waqar/declaration-use-variable` would probably be good options.

**Comment by bdukes** [comment]
The SSCCE in #7 also demonstrates this issue

**Comment by sh-waqar** [comment]
@bdukes - Thanks for reporting the issue. I will look into it.

**Comment by reintroducing** [comment]
also just ran into this. any updates on this?

**Comment by nicothin** [comment]
is a great plugin!
really I want to make it work.
an important problem.

**Comment by sh-waqar** [comment]
@bdukes @nicothin and other who were facing this issue. Please update and let me know if you find any issues. Thanks.

**Comment by sh-waqar** [comment]
Please reopen the issue if it still persists.

**Comment by nicothin** [comment]
@sh-waqar all is ok
waiting for the update npm-package )
